In [0]:
#Import libraries
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0'

In [0]:
#Import dataset
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [5]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [0]:
#Splitting the dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [0]:
#Initialise ANN
ann = tf.keras.models.Sequential()

In [0]:
#Add input layer and first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [0]:
#Add second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [0]:
#Add output layer
ann.add(tf.keras.layers.Dense(units=1))

In [0]:
#Compile ANN
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [12]:
#Train ANN
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 0s 1ms/step - loss: 17669.9023
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 176.0411
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 171.8261
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 166.3773
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 160.2201
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 152.9186
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 145.1847
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 137.3156
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 128.6412
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 119.9693
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 111.3477
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - lo

In [13]:
#Prediction
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[431.51 431.23]
 [462.35 460.01]
 [465.8  461.14]
 ...
 [473.02 473.26]
 [439.97 438.  ]
 [459.06 463.28]]
